var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var BAC01Router = require("./routes/BAC01");
var BAC02Router = require("./routes/BAC02");
var BAC03Router = require("./routes/BAC03");
var BAC04Router = require("./routes/BAC04");
var BAC05Router = require("./routes/BAC05");
var BAC06Router = require("./routes/BAC06");
var BAC10Router = require("./routes/BAC10");
var BAC11Router = require("./routes/BAC11");
var BAC12Router = require("./routes/BAC12");
var BAC17Router = require("./routes/BAC17");
var BAC17ValoresRouter = require("./routes/BAC17Valores");
var BAC18Router = require("./routes/BAC18");
var BAC19Router = require("./routes/BAC19");
var BAC20Router = require("./routes/BAC20");
var BAC20MetasRouter = require("./routes/BAC20Metas");
var BAC20ObjetivosRouter = require("./routes/BAC20Objetivos");
var BAC21Router = require("./routes/BAC21");
var BAC22Router = require("./routes/BAC22");
var BAC23Router = require("./routes/BAC23");
var BAC26Router = require("./routes/BAC26");
var BAC27Router = require("./routes/BAC27");
var BAC28Router = require("./routes/BAC28");
var BAC29Router = require("./routes/BAC29");
var BAC30Router = require("./routes/BAC30");
var BAC31Router = require("./routes/BAC31");
var BAC32Router = require("./routes/BAC32");
var BAC33Router = require("./routes/BAC33");
var BAC34Router = require("./routes/BAC34");
var BAC35Router = require("./routes/BAC35");
var BAC54Router = require("./routes/BAC54");
var BAC55BalanceRouter = require("./routes/BAC55Balance");
var BAC55FlujoCajaRouter = require("./routes/BAC55FlujoCaja");
var BAC55IngresosEgresosRouter = require("./routes/BAC55IngresosEgresos");
var BAC56CargosRouter = require("./routes/BAC56Cargos");
var BAC56ComitesRouter = require("./routes/BAC56Comites");
var BAC56FuncionesRouter = require("./routes/BAC56Funciones");
var BAC56FuncionesComiteRouter = require("./routes/BAC56FuncionesComite");
var BAC56ServiciosInternosRouter = require("./routes/BAC56ServiciosInternos");
var BAC56UnidadesNegocioRouter = require("./routes/BAC56UnidadesNegocio");
var BAC56UnidadesSoporteRouter = require("./routes/BAC56UnidadesSoporte");
var BAC57PrimariosRouter = require("./routes/BAC57Primarios");
var BAC57SoporteRouter = require("./routes/BAC57Soporte");
var BAC58Router = require("./routes/BAC58");
var BAC59Router = require("./routes/BAC59");
var BAC60BRouter = require("./routes/BAC60B");
var BAC60BActividadesRouter = require("./routes/BAC60BActividades");
var BAC60BConceptosRouter = require("./routes/BAC60BConceptos");
var BAC61BRouter = require("./routes/BAC61B");
var BAC61BActividadesRouter = require("./routes/BAC61BActividades");
var BAC61BConceptosRouter = require("./routes/BAC61BConceptos");
var BAC62ARouter = require("./routes/BAC62A");
var BAC62BRouter = require("./routes/BAC62B");
var BAC62BInterfazRouter = require("./routes/BAC62BInterfaz");
var BAC62BServiciosRouter = require("./routes/BAC62BServicios");
var BAC62CRouter = require("./routes/BAC62C");
var BAC62CModulosRouter = require("./routes/BAC62CModulos");
var BAC62DRouter = require("./routes/BAC62D");
var BAC62ERouter = require("./routes/BAC62E");
var BAC62FRouter = require("./routes/BAC62F");
var BAC62GRouter = require("./routes/BAC62G");
var BAC62GInterfazRouter = require("./routes/BAC62GInterfaz");
var BAC62GOrganizacionRouter = require("./routes/BAC62GOrganizacion");
var BAC62GServiciosRouter = require("./routes/BAC62GServicios");
var BAC62HRouter = require("./routes/BAC62H");
var BAC62IRouter = require("./routes/BAC62I");
var BAC63Router = require("./routes/BAC63");
var BAC63IndicadoresExternosRouter = require("./routes/BAC63IndicadoresExternos");
var BAC64Router = require("./routes/BAC64");
var BAC67ARouter = require("./routes/BAC67A");
var BAC67BRouter = require("./routes/BAC67B");
var BAC67BInterfazRouter = require("./routes/BAC67BInterfaz");
var BAC67BServiciosRouter = require("./routes/BAC67BServicios");
var BAC67CRouter = require("./routes/BAC67C");
var BAC67DRouter = require("./routes/BAC67D");
var BAC67ERouter = require("./routes/BAC67E");
var BAC68BRouter = require("./routes/BAC68B");
var BAC68CRouter = require("./routes/BAC68C");
var BAC69ACapacidadRouter = require("./routes/BAC69ACapacidad");
var BAC69AFuncionalidadesRouter = require("./routes/BAC69AFuncionalidades");
var BAC69BRouter = require("./routes/BAC69B");
var clienteRouter = require("./routes/cliente");
var proveedorSoporteRouter = require ("./routes/proveedorSoporte");
var proyecto = require("./routes/proyecto");

const sequelize = require("./lib/sequelize");
sequelize.sync();

var app = express();

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));


app.use("/api/BAC01", BAC01Router);
app.use("/api/BAC02", BAC02Router);
app.use("/api/BAC03", BAC03Router);
app.use("/api/BAC04", BAC04Router);
app.use("/api/BAC05", BAC05Router);
app.use("/api/BAC06", BAC06Router);
app.use("/api/BAC10", BAC10Router);
app.use("/api/BAC11", BAC11Router);
app.use("/api/BAC12", BAC12Router);
app.use("/api/BAC17", BAC17Router);
app.use("/api/BAC17Valores", BAC17ValoresRouter);
app.use("/api/BAC18", BAC18Router);
app.use("/api/BAC19", BAC19Router);
app.use("/api/BAC20", BAC20Router);
app.use("/api/BAC20Metas", BAC20MetasRouter);
app.use("/api/BAC20Objetivos", BAC20ObjetivosRouter);
app.use("/api/BAC21", BAC21Router);
app.use("/api/BAC22", BAC22Router);
app.use("/api/BAC23", BAC23Router);
app.use("/api/BAC26", BAC26Router);
app.use("/api/BAC27", BAC27Router);
app.use("/api/BAC28", BAC28Router);
app.use("/api/BAC29", BAC29Router);
app.use("/api/BAC30", BAC30Router);
app.use("/api/BAC31", BAC31Router);
app.use("/api/BAC32", BAC32Router);
app.use("/api/BAC33", BAC33Router);
app.use("/api/BAC34", BAC34Router);
app.use("/api/BAC35", BAC35Router);
app.use("/api/BAC54", BAC54Router);
app.use("/api/BAC55Balance",BAC55BalanceRouter);
app.use("/api/BAC55FlujoCaja",BAC55FlujoCajaRouter);
app.use("/api/BAC55IngresosEgresos",BAC55IngresosEgresosRouter);
app.use("/api/BAC56Cargos",BAC56CargosRouter);
app.use("/api/BAC56Comites",BAC56ComitesRouter);
app.use("/api/BAC56Funciones",BAC56FuncionesRouter);
app.use("/api/BAC56FuncionesComite",BAC56FuncionesComiteRouter);
app.use("/api/BAC56ServiciosInternos",BAC56ServiciosInternosRouter);
app.use("/api/BAC56UnidadesNegocio",BAC56UnidadesNegocioRouter);
app.use("/api/BAC56UnidadesSoporte",BAC56UnidadesSoporteRouter);
app.use("/api/BAC57Primarios",BAC57PrimariosRouter);
app.use("/api/BAC57Soporte",BAC57SoporteRouter);
app.use("/api/BAC58", BAC58Router);
app.use("/api/BAC59",BAC59Router);
app.use("/api/BAC60B",BAC60BRouter);
app.use("/api/BAC60BActividades",BAC60BActividadesRouter);
app.use("/api/BAC60BConceptos",BAC60BConceptosRouter);
app.use("/api/BAC61B",BAC61BRouter);
app.use("/api/BAC61BActividades",BAC61BActividadesRouter);
app.use("/api/BAC61BConceptos",BAC61BConceptosRouter);
app.use("/api/BAC62A",BAC62ARouter);
app.use("/api/BAC62B",BAC62BRouter);
app.use("/api/BAC62BInterfaz",BAC62BInterfazRouter);
app.use("/api/BAC62BServicios",BAC62BServiciosRouter);
app.use("/api/BAC62C",BAC62CRouter);
app.use("/api/BAC62CModulos",BAC62CModulosRouter);
app.use("/api/BAC62D",BAC62DRouter);
app.use("/api/BAC62E",BAC62ERouter);
app.use("/api/BAC62F",BAC62FRouter);
app.use("/api/BAC62G",BAC62GRouter);
app.use("/api/BAC62GInterfaz",BAC62GInterfazRouter);
app.use("/api/BAC62GOrganizacion",BAC62GOrganizacionRouter);
app.use("/api/BAC62GServicios",BAC62GServiciosRouter);
app.use("/api/BAC62H",BAC62HRouter);
app.use("/api/BAC62I",BAC62IRouter);
app.use("/api/BAC63",BAC63Router);
app.use("/api/BAC63IndicadoresExternos",BAC63IndicadoresExternosRouter);
app.use("/api/BAC64",BAC64Router);
app.use("/api/BAC67A",BAC67ARouter);
app.use("/api/BAC67B",BAC67BRouter);
app.use("/api/BAC67BInterfaz",BAC67BInterfazRouter);
app.use("/api/BAC67BServicios",BAC67BServiciosRouter);
app.use("/api/BAC67C",BAC67CRouter);
app.use("/api/BAC67D",BAC67DRouter);
app.use("/api/BAC67E",BAC67ERouter);
app.use("/api/BAC68B",BAC68BRouter);
app.use("/api/BAC68C",BAC68CRouter);
app.use("/api/BAC69ACapacidad",BAC69ACapacidadRouter);
app.use("/api/BAC69AFuncionalidades",BAC69AFuncionalidadesRouter);
app.use("/api/BAC69B",BAC69BRouter);
app.use("/api/cliente",clienteRouter);
app.use("/api/proveedorSoporte",proveedorSoporteRouter);
app.use("/api/proyecto", proyecto);

module.exports = app;
